#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: All
on:
  workflow_dispatch:
#  schedule:
#  - cron: 0 14 *  * 2,4,6
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:      
    - name: Trigger build
      uses: peter-evans/repository-dispatch@v1
      with:
       token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
       event-type: All

